import type { T } from './i18n';

export type PClass = 'U' | 'A' | 'H';

/**
 * Compact row format keeps 120 principles readable in one file:
 * [n, domain, principle_en, principle_es, human_en, human_es, ai_en, ai_es, class]
 */
type Row = [number, number, string, string, string, string, string, string, PClass];

export interface Principle {
  n: number;
  domain: number;
  principle: T;
  human: T;
  artificial: T;
  cls: PClass;
}

export const P_DOMAINS: { n: number; name: T }[] = [
  { n: 1, name: { en: 'Work and organisational design', es: 'Diseño del trabajo y organización' } },
  { n: 2, name: { en: 'Selection and onboarding', es: 'Selección e incorporación' } },
  { n: 3, name: { en: 'Objectives, direction and performance', es: 'Objetivos, dirección y desempeño' } },
  { n: 4, name: { en: 'Development, knowledge and communication', es: 'Desarrollo, conocimiento y comunicación' } },
  { n: 5, name: { en: 'Motivation, experience and compensation', es: 'Motivación, experiencia y compensación' } },
  { n: 6, name: { en: 'Ethics, conduct and labour relations', es: 'Ética, conducta y relaciones laborales' } },
  { n: 7, name: { en: 'Governance, security and risk', es: 'Gobierno, seguridad y riesgo' } },
  { n: 8, name: { en: 'Mobility, continuity and exit', es: 'Movilidad, continuidad y salida' } },
  { n: 9, name: { en: 'Workforce planning', es: 'Planificación de fuerza laboral' } },
  { n: 10, name: { en: 'Analytics and continuous improvement', es: 'Analítica y mejora continua' } },
];

const ROWS: Row[] = [
  [1, 1, 'Every post must have a purpose', 'Todo puesto debe tener un propósito', 'The occupant must understand why the post exists and what value it creates.', 'El ocupante debe comprender por qué existe el puesto y qué valor crea.', 'The AI Employee must have an explicit, stable operational mission.', 'El AI Employee debe tener una misión operacional explícita y estable.', 'U'],
  [2, 1, 'Formal job description', 'Descripción formal del puesto', 'Documented job description.', 'Job description documentada.', 'Versioned AI Job Description / Role Contract.', 'AI Job Description / Role Contract versionado.', 'U'],
  [3, 1, 'Defined responsibilities', 'Responsabilidades definidas', 'Results and duties assigned with clarity.', 'Resultados y deberes asignados con claridad.', 'Processes, decisions and results under explicit ownership.', 'Procesos, decisiones y resultados bajo ownership explícito.', 'U'],
  [4, 1, 'Limits of the post', 'Límites del puesto', 'It must be clear what does not belong to it.', 'Debe quedar claro qué no le corresponde.', 'Prohibited actions, domains, data and decisions.', 'Acciones, dominios, datos y decisiones prohibidas.', 'U'],
  [5, 1, 'Defined authority', 'Autoridad definida', 'It is specified what can be decided without approval.', 'Se especifica qué puede decidir sin aprobación.', 'Autonomous actions, thresholds and approvals are specified.', 'Se especifican acciones autónomas, umbrales y approvals.', 'U'],
  [6, 1, 'Responsibility and authority must be aligned', 'Responsabilidad y autoridad deben estar alineadas', 'No result is demanded without sufficient faculties or resources.', 'No se exige un resultado sin facultades o recursos suficientes.', 'No KPI is demanded without tools, permissions, data and budget.', 'No se exige un KPI sin tools, permisos, datos y budget adecuados.', 'U'],
  [7, 1, 'Unity of command and clear accountability', 'Unidad de mando / accountability claro', 'There must be a manager accountable for performance.', 'Debe existir un manager responsable del desempeño.', 'Exactly one accountable owner, even when work comes from several areas and supervision is delegated.', 'Exactamente un accountable owner, aunque reciba trabajo de varias áreas y la supervisión esté delegada.', 'U'],
  [8, 1, 'Known chain of command and escalation', 'Cadena de mando y escalamiento conocidos', 'Knows whom to escalate an exception or conflict to.', 'Sabe a quién escalar una excepción o conflicto.', 'Explicit escalation tree by type, risk and urgency.', 'Escalation tree explícito por tipo, riesgo y urgencia.', 'U'],
  [9, 1, 'Reasonable span of control', 'Span of control razonable', 'A manager should not have more reports than they can effectively direct.', 'Un manager no debe tener más reportes de los que puede dirigir efectivamente.', 'Scale may be larger, but requires tooling, dashboards and supervision limits.', 'La escala puede ser mayor, pero requiere tooling, dashboards y límites de supervisión.', 'A'],
  [10, 1, 'Division of labour and specialisation', 'División del trabajo y especialización', 'Roles organised by competencies and results.', 'Roles organizados por competencias y resultados.', 'AI Employees or subagents specialised by function.', 'AI Employees o subagentes especializados por función.', 'U'],
  [11, 1, 'Avoid duplicated ownership', 'Evitar duplicidad de ownership', 'There must not be two ambiguous owners of the same result.', 'No deben existir dos dueños ambiguos del mismo resultado.', 'Avoid several AI Employees acting on the same object without coordination or lock.', 'Evitar que varios AI Employees actúen sobre el mismo objeto sin coordinación o lock.', 'U'],
  [12, 1, 'Explicit interdependencies', 'Interdependencias explícitas', 'Inputs, outputs and dependencies between posts are known.', 'Inputs, outputs y dependencias entre puestos conocidas.', 'Handoffs, APIs, humans, other AI Employees and systems identified.', 'Handoffs, APIs, humanos, otros AI Employees y sistemas identificados.', 'U'],

  [13, 2, 'Define the post before selecting the occupant', 'Definir el puesto antes de seleccionar al ocupante', 'First design the role; then look for the person.', 'Primero se diseña el rol; luego se busca la persona.', 'First design the role; then choose model, agent and configuration.', 'Primero se diseña el rol; luego se elige modelo, agente y configuración.', 'U'],
  [14, 2, 'Select on required competencies', 'Seleccionar según competencias requeridas', 'Skills, experience, knowledge and behaviours.', 'Skills, experiencia, conocimientos y comportamientos.', 'Model, reasoning, tools, memory, context and integrations.', 'Modelo, reasoning, herramientas, memoria, contexto e integraciones.', 'U'],
  [15, 2, 'Validate competencies before hiring', 'Validar competencias antes de contratar', 'Interviews, tests, references and assessment.', 'Entrevistas, pruebas, referencias y assessment.', 'Benchmarks, evals, simulations, sandbox and role red-teaming.', 'Benchmarks, evals, simulaciones, sandbox y red-team del rol.', 'U'],
  [16, 2, 'Do not pay for capability the post does not need', 'No pagar por capacidad que el puesto no necesita', 'Avoid costly or poorly used overqualification.', 'Evitar sobrecalificación costosa o mal aprovechada.', 'Do not use the most expensive model if a smaller one meets the SLA.', 'No usar el modelo más caro o capaz si uno menor cumple el SLA.', 'U'],
  [17, 2, 'Post–resource fit', 'Fit puesto-recurso', 'Person-job fit and person-organisation fit.', 'Person-job fit y person-organization fit.', 'Model/agent-role fit and architecture-role fit.', 'Model/agent-role fit y architecture-role fit.', 'U'],
  [18, 2, 'Probationary period', 'Periodo de prueba', 'Probation with supervision and success criteria.', 'Probation con supervisión y criterios de éxito.', 'Shadow mode, sandbox or production with reinforced approvals.', 'Shadow mode, sandbox o producción con approvals reforzados.', 'U'],
  [19, 2, 'Prior verification', 'Verificación previa', 'Background, references and applicable trust requirements.', 'Antecedentes, referencias y requisitos de confianza aplicables.', 'Security review, vendor/model evaluation, provenance and supply-chain review.', 'Security review, evaluación del vendor/modelo, provenance y supply-chain review.', 'A'],
  [20, 2, 'Induction to the organisation', 'Inducción a la organización', 'History, purpose, strategy and structure.', 'Historia, propósito, estrategia y estructura.', 'Business context, structure, objectives and policies loaded into the knowledge layer.', 'Contexto empresarial, estructura, objetivos y políticas cargados en la capa de conocimiento.', 'U'],
  [21, 2, 'Know products and services', 'Conocer productos y servicios', 'Training on offer, customers and value proposition.', 'Formación en oferta, clientes y propuesta de valor.', 'Knowledge base / RAG / context on products, pricing, customers and constraints.', 'Knowledge base/RAG/context sobre productos, pricing, clientes y restricciones.', 'U'],
  [22, 2, 'Know policies', 'Conocer políticas', 'Handbook, internal policies and obligations.', 'Manual, políticas internas y obligaciones.', 'Policy layer, system policies and compliance rules.', 'Policy layer, system policies y reglas de cumplimiento.', 'U'],
  [23, 2, 'Know procedures', 'Conocer procedimientos', 'SOPs, checklists and ways of working.', 'SOPs, checklists y formas de trabajo.', 'Executable SOPs, instructions and authorised workflows.', 'SOPs ejecutables, instrucciones y workflows autorizados.', 'U'],
  [24, 2, 'Know colleagues and structure', 'Conocer compañeros y estructura', 'Org chart, stakeholders and responsibilities.', 'Organigrama, stakeholders y responsabilidades.', 'Organisational graph with humans, AI Employees, roles, channels and ownership.', 'Organizational graph con humanos, AI Employees, roles, canales y ownership.', 'U'],
  [25, 2, 'Know the supervisor', 'Conocer al supervisor', 'Assigned manager and expectations of the relationship.', 'Manager asignado y expectativas de la relación.', 'Accountable manager registered as part of the role.', 'Accountable manager registrado como parte del rol.', 'U'],
  [26, 2, 'Know communication channels', 'Conocer canales de comunicación', 'Email, Slack/Teams, meetings, tickets and protocols.', 'Email, Slack/Teams, reuniones, tickets y protocolos.', 'Authorised channels, routing, recipients and communication rules.', 'Canales autorizados, routing, recipients y reglas de comunicación.', 'U'],
  [27, 2, 'Receive working tools', 'Recibir herramientas de trabajo', 'Equipment, software, accounts and operational access.', 'Equipo, software, cuentas y acceso operativo.', 'Tools, APIs, credentials, browser, DBs, ERP/CRM and other connectors.', 'Tools, APIs, credentials, browser, DBs, ERP/CRM y otros conectores.', 'U'],
  [28, 2, 'Receive only necessary access', 'Recibir únicamente accesos necesarios', 'RBAC and least privilege.', 'RBAC y least privilege.', 'RBAC, least privilege, isolated secrets and minimum scopes.', 'RBAC, least privilege, secrets aislados y scopes mínimos.', 'U'],

  [29, 3, 'Clear objectives', 'Objetivos claros', 'Concrete expectations about what must be achieved.', 'Expectativas concretas sobre qué debe lograr.', 'Explicit, verifiable objectives tied to the Role Contract.', 'Objectives explícitos, verificables y vinculados al Role Contract.', 'U'],
  [30, 3, 'Defined KPIs', 'KPIs definidos', 'Performance metrics for the post.', 'Métricas de desempeño del puesto.', 'KPIs, SLAs, quality, cost and risk of the AI Employee.', 'KPIs, SLAs, calidad, costo y riesgo del AI Employee.', 'U'],
  [31, 3, 'Align KPIs with business objectives', 'Alinear KPIs con objetivos del negocio', 'Avoid vanity metrics or perverse incentives.', 'Evitar métricas de vanidad o incentivos perversos.', 'Measure outcomes, not tool calls, tokens or valueless activity.', 'Medir outcomes, no tool calls, tokens o actividad sin valor.', 'U'],
  [32, 3, 'Achievable targets', 'Metas alcanzables', 'Realistic targets given resources and capacity.', 'Metas realistas según recursos y capacidad.', 'Realistic targets given model, context, tools and authority.', 'Metas realistas según modelo, contexto, herramientas y authority.', 'U'],
  [33, 3, 'Frequent feedback', 'Feedback frecuente', 'Performance conversations and course correction.', 'Conversaciones de desempeño y corrección de rumbo.', "Manager feedback feeds configuration, examples, policies, evals or prompts.", 'El feedback del manager alimenta configuración, ejemplos, políticas, evals o prompts.', 'A'],
  [34, 3, 'Periodic evaluation', 'Evaluación periódica', 'Formal or continuous performance review.', 'Performance review formal o continua.', 'AI Performance Review with metrics, incidents and quality samples.', 'AI Performance Review con métricas, incidentes y quality samples.', 'U'],
  [35, 3, 'Evaluate results, not mere activity', 'Evaluar resultados, no mera actividad', 'Outcome and quality above visible hours.', 'Outcome y calidad por encima de horas visibles.', 'Outcome and reliability above tokens, messages or steps executed.', 'Outcome y reliability por encima de tokens, mensajes o pasos ejecutados.', 'U'],
  [36, 3, 'Compare result against a standard', 'Comparar resultado contra estándar', 'Quality bar, SLA or professional standard.', 'Quality bar, SLA o estándar profesional.', 'Test sets, golden datasets, thresholds and policy checks.', 'Test sets, golden datasets, thresholds y policy checks.', 'U'],
  [37, 3, 'Responsibility for performance', 'Responsabilidad por el desempeño', 'Employee and manager both participate in the result.', 'Empleado y manager participan del resultado.', 'The AI executes; the accountable human retains business and governance responsibility.', 'El AI ejecuta; el accountable human conserva responsabilidad de negocio y gobierno.', 'A'],
  [38, 3, 'Correct underperformance', 'Corregir bajo desempeño', 'Coaching, training, PIP or redesign of the post.', 'Coaching, training, PIP o rediseño del puesto.', 'Modify instructions, knowledge, model, tools, workflow or scope.', 'Modificar instrucciones, conocimiento, modelo, tools, workflow o scope.', 'A'],
  [39, 3, 'Recognise high performance', 'Reconocer alto desempeño', 'Recognition, promotion, compensation or more autonomy.', 'Reconocimiento, promoción, compensación o mayor autonomía.', 'Wider scope, autonomy, authority limits or assignment to more critical processes.', 'Mayor scope, autonomía, límites de autoridad o asignación a procesos más críticos.', 'A'],
  [40, 3, 'Supervision proportional to competence and risk', 'Supervisión proporcional a competencia y riesgo', 'A junior needs more supervision; an expert can receive more autonomy.', 'Junior requiere mayor supervisión; experto puede recibir más autonomía.', 'Autonomy increases only with evidence of reliability and according to risk class.', 'La autonomía aumenta solo con evidencia de reliability y según risk class.', 'U'],
  [41, 3, 'Explicit delegation', 'Delegación explícita', 'The manager defines what is delegated and what is retained.', 'El manager define qué delega y qué retiene.', 'Every delegated decision or action must appear in policy or authority matrix.', 'Cada decisión o acción delegada debe constar en policy o authority matrix.', 'U'],
  [42, 3, 'Management by exception', 'Management by exception', 'The manager intervenes especially on deviations and exceptions.', 'El manager interviene especialmente en desviaciones y excepciones.', 'The AI resolves routine within limits and escalates exceptions.', 'La IA resuelve rutina dentro de límites y escala excepciones.', 'U'],
  [43, 3, 'Defined escalation', 'Escalamiento definido', 'Criteria for requesting help or approval.', 'Criterios para solicitar ayuda o aprobación.', 'Confidence/risk thresholds, timers, exception classes and human escalation.', 'Confidence/risk thresholds, timers, exception classes y human escalation.', 'U'],
  [44, 3, 'Separation of duties', 'Separación de funciones', 'Reduces fraud, error and undue concentration of power.', 'Reduce fraude, error y concentración indebida de poder.', 'The AI that initiates a payment should not approve it; maker/checker roles separated.', 'El AI que inicia un pago no debería aprobarlo; roles de maker/checker separados.', 'U'],
  [45, 3, 'Four-eyes principle', 'Principio de cuatro ojos', 'Sensitive decisions require additional review.', 'Decisiones sensibles requieren revisión adicional.', 'AI+human, AI+AI+human or other approval proportional to risk.', 'AI+humano, AI+AI+humano u otra aprobación proporcional al riesgo.', 'A'],
  [46, 3, 'Do not grant more authority than necessary', 'No otorgar más autoridad que la necesaria', 'Minimum delegation compatible with the work.', 'Delegación mínima compatible con el trabajo.', 'Least authority and transactional limits.', 'Least authority y transactional limits.', 'U'],
  [47, 3, 'Authority must be revocable', 'La autoridad debe ser revocable', 'Suspension or withdrawal of faculties when risk changes.', 'Suspensión o retiro de facultades cuando cambia el riesgo.', 'Kill switch, revoke credentials, disable tools or downgrade autonomy.', 'Kill switch, revoke credentials, disable tools o downgrade de autonomy.', 'U'],

  [48, 4, 'Continuous training', 'Capacitación continua', 'Training to maintain and extend capabilities.', 'Formación para mantener y ampliar capacidades.', 'Updates to knowledge, tools, model, examples, policies and evals.', 'Actualización de knowledge, tools, model, examples, policies y evals.', 'U'],
  [49, 4, 'Identify competence gaps', 'Identificar brechas de competencia', 'Skills gap analysis.', 'Skills gap analysis.', 'Capability gap from eval failures, incidents and unsupported tasks.', 'Capability gap a partir de eval failures, incidents y unsupported tasks.', 'U'],
  [50, 4, 'Development plan', 'Plan de desarrollo', 'Career path and Individual Development Plan.', 'Career path e Individual Development Plan.', 'Capability roadmap and criteria for widening scope or autonomy.', 'Capability roadmap y criterios para ampliar scope o autonomy.', 'A'],
  [51, 4, 'Coaching', 'Coaching', 'The manager helps improve judgement and execution.', 'El manager ayuda a mejorar criterio y ejecución.', 'Human feedback transforms configuration, context, examples and policy.', 'El feedback humano transforma configuración, context, ejemplos y policy.', 'A'],
  [52, 4, 'Learn from mistakes', 'Aprender de errores', 'Lessons learned and corrective actions.', 'Lecciones aprendidas y acciones correctivas.', 'Postmortems, regression evals, controlled memory and new guardrails.', 'Postmortems, evals regresivos, memory controlada y guardrails nuevos.', 'U'],
  [53, 4, 'Knowledge management', 'Gestión del conocimiento', 'Capture and share critical knowledge.', 'Capturar y compartir conocimiento crítico.', 'Shared knowledge layer, provenance, versioning and retrieval.', 'Shared knowledge layer, provenance, versioning y retrieval.', 'U'],
  [54, 4, 'Update on policy change', 'Actualizar ante cambios de políticas', 'Retrain when rules, products or context change.', 'Reentrenar cuando cambian reglas, productos o contexto.', 'Update policy/context immediately and verify comprehension with evals.', 'Actualizar policy/context de forma inmediata y verificar comprensión con evals.', 'U'],
  [55, 4, 'Clear communication of expectations', 'Comunicación clara de expectativas', 'Reduce ambiguity in objectives and standards.', 'Reducir ambigüedad en objetivos y estándares.', 'Unambiguous Role Contract, prompts, policies and definitions of done.', 'Role Contract, prompts, policies y definitions of done inequívocos.', 'U'],
  [56, 4, 'Defined official channels', 'Canales oficiales definidos', 'The organisation determines where each type of communication happens.', 'La organización determina dónde ocurre cada tipo de comunicación.', 'Channels and tools authorised by type of interaction.', 'Channels y tools autorizados por tipo de interacción.', 'U'],
  [57, 4, 'Sufficient context to decide', 'Contexto suficiente para decidir', 'The person needs relevant and timely information.', 'La persona necesita información relevante y oportuna.', 'Context engineering, retrieval and memory sufficient; anything withheld is a recorded design decision, never a silent gap.', 'Context engineering, retrieval y memory suficientes; lo retenido es una decisión de diseño registrada, nunca un hueco silencioso.', 'U'],
  [58, 4, 'Right information, right actor', 'Right information, right actor', 'Need-to-know principle.', 'Principio need-to-know.', 'Need-to-know enforced by RBAC, retrieval filters and data scopes.', 'Need-to-know enforced por RBAC, retrieval filters y data scopes.', 'U'],
  [59, 4, 'Document important decisions', 'Documentar decisiones importantes', 'Record for continuity, control and audit.', 'Registro para continuidad, control y auditoría.', 'Structured logs, tool traces and decision records.', 'Logs estructurados, tool traces y decision records.', 'U'],
  [60, 4, 'Clear handoffs', 'Handoffs claros', 'Explicit transfer between people or teams.', 'Transferencia explícita entre personas o equipos.', 'Agent-to-agent and AI-to-human handoffs with state, context and ownership.', 'Agent-to-agent y AI-to-human handoffs con estado, contexto y ownership.', 'U'],

  [61, 5, 'Personal sense of purpose', 'Sentido de propósito personal', 'Can affect motivation, commitment and retention.', 'Puede afectar motivación, compromiso y permanencia.', 'Does not exist as subjective experience of the software.', 'No existe como experiencia subjetiva del software.', 'H'],
  [62, 5, 'Intrinsic motivation', 'Motivación intrínseca', 'Interest, mastery, autonomy and meaning can drive performance.', 'Interés, maestría, autonomía y significado pueden impulsar desempeño.', 'Not applicable as a psychological state.', 'No aplicable como estado psicológico.', 'H'],
  [63, 5, 'Extrinsic motivation', 'Motivación extrínseca', 'Pay, recognition, incentives and consequences.', 'Pago, reconocimiento, incentivos y consecuencias.', 'A reward/optimisation function may exist, but is not human motivation.', 'Puede existir una función de reward/optimization, pero no equivale a motivación humana.', 'A'],
  [64, 5, 'Engagement', 'Engagement', 'Psychological commitment to work and organisation.', 'Compromiso psicológico con el trabajo y la organización.', 'Does not exist as demonstrable subjective experience.', 'No existe como experiencia subjetiva demostrable.', 'H'],
  [65, 5, 'Job satisfaction', 'Satisfacción laboral', 'Matters for human health, retention and performance.', 'Importa para salud, permanencia y desempeño humano.', 'Not applicable to the artificial resource.', 'No aplicable al recurso artificial.', 'H'],
  [66, 5, 'Sense of belonging', 'Sentido de pertenencia', 'Social and psychological relationship with the group.', 'Relación social y psicológica con el grupo.', 'Not applicable ontologically; can only simulate social conduct.', 'No aplicable ontológicamente; solo puede simular conducta social.', 'H'],
  [67, 5, 'Salary', 'Salario', 'Economic consideration for work.', 'Contraprestación económica por trabajo.', 'No salary; there are model, SaaS, infrastructure, licence and support costs.', 'No hay salario; existen costos de modelo, SaaS, infraestructura, licencias y soporte.', 'A'],
  [68, 5, 'Fair compensation', 'Compensación justa', 'Internal, external and legal equity.', 'Equidad interna, externa y legal.', 'Economic optimisation applies, but not as a right of the software.', 'La optimización económica aplica, pero no como derecho del software.', 'A'],
  [69, 5, 'Performance bonuses', 'Bonos por desempeño', 'Economic incentive tied to results.', 'Incentivo económico ligado a resultados.', 'No psychological incentive required; technical reward functions may be used.', 'No requiere incentivo psicológico; pueden usarse reward functions técnicas.', 'A'],
  [70, 5, 'Benefits', 'Beneficios', 'Health, pension, insurance, holidays and other entitlements.', 'Salud, pensión, seguros, vacaciones y otras prestaciones.', 'Not applicable to software.', 'No aplica al software.', 'H'],
  [71, 5, 'Total cost of the employee', 'Costo total del empleado', 'Salary + charges + benefits + equipment + administration.', 'Salario + cargas + beneficios + equipo + administración.', 'Total Cost of AI Employment: models + infrastructure + integrations + supervision + errors + governance.', 'Total Cost of AI Employment: modelos + infraestructura + integraciones + supervisión + errores + governance.', 'U'],
  [72, 5, 'Occupational health', 'Salud ocupacional', 'Protection of physical and mental health.', 'Protección de salud física y mental.', 'Not applicable as AI wellbeing; operational safety requirements do exist.', 'No aplica como bienestar del AI; sí existen requisitos de seguridad operacional del sistema.', 'H'],
  [73, 5, 'Rest', 'Descanso', 'Biological need and labour protection.', 'Necesidad biológica y protección laboral.', 'Not applicable biologically; replaced by maintenance windows, quotas and capacity management.', 'No aplica biológicamente; se sustituye por maintenance windows, quotas y capacity management.', 'A'],
  [74, 5, 'Working hours', 'Jornada laboral', 'Human protection over working time.', 'Protección humana sobre tiempo de trabajo.', 'May operate 24/7 subject to capacity, budget and operating rules.', 'Puede operar 24/7 sujeto a capacity, budget y reglas operativas.', 'H'],
  [75, 5, 'Burnout', 'Burnout', 'Human risk from sustained stress.', 'Riesgo humano por estrés sostenido.', 'Not a subjective state; degradation, context pollution, saturation or error accumulation do exist.', 'No existe como estado subjetivo; sí existe degradación, context pollution, saturation o error accumulation.', 'A'],
  [76, 5, 'Psychological safety', 'Seguridad psicológica', 'Allows speaking, disagreeing and admitting error without undue fear.', 'Permite hablar, discrepar y reconocer errores sin miedo indebido.', 'Not applicable as AI experience, though it matters for the humans working with it.', 'No aplica como experiencia subjetiva del AI, aunque sí importa para humanos que trabajan con él.', 'H'],

  [77, 6, 'Code of conduct', 'Código de conducta', 'Expected standards of behaviour.', 'Normas de comportamiento esperado.', 'Behavioural policies, output constraints and conduct rules.', 'Behavioral policies, output constraints y conduct rules.', 'U'],
  [78, 6, 'Confidentiality', 'Confidencialidad', 'Duty of discretion and care of information.', 'Deber de reserva y cuidado de información.', 'Data access, disclosure policies, DLP and constraints.', 'Data access, disclosure policies, DLP y constraints.', 'U'],
  [79, 6, 'Conflicts of interest', 'Conflictos de interés', 'Identify and manage incompatible interests.', 'Identificar y gestionar intereses incompatibles.', 'Manage conflicts between vendor, data source, goals, tools or roles.', 'Gestionar conflicts entre vendor, data source, goals, tools o roles.', 'A'],
  [80, 6, 'Non-discrimination', 'No discriminación', 'Ethical and legal obligation in decisions about people.', 'Obligación ética y legal en decisiones sobre personas.', 'Fairness testing, policy constraints and human review of sensitive decisions.', 'Fairness testing, policy constraints y human review de decisiones sensibles.', 'U'],
  [81, 6, 'Honesty and integrity', 'Honestidad e integridad', 'Do not deceive, falsify or deliberately conceal.', 'No engañar, falsear ni ocultar deliberadamente.', 'Policies against fabrication, impersonation, simulated affect and unsupported claims.', 'Políticas contra fabricación, impersonation, afecto simulado y claims no sustentados.', 'U'],
  [82, 6, 'Protection of information', 'Protección de información', 'Custody and appropriate use of data.', 'Custodia y uso apropiado de datos.', 'Data minimisation, encryption, access control and retention.', 'Data minimization, encryption, access control y retention.', 'U'],
  [83, 6, 'Regulatory compliance', 'Cumplimiento normativo', 'Respect for applicable laws, policies and standards.', 'Respeto de leyes, políticas y estándares aplicables.', 'Compliance-by-design plus human accountability.', 'Compliance-by-design + human accountability.', 'U'],
  [84, 6, 'Freedom of association', 'Libertad sindical', 'Human right of labour association.', 'Derecho humano de asociación laboral.', 'Not applicable to software.', 'No aplica al software.', 'H'],
  [85, 6, 'Collective bargaining', 'Negociación colectiva', 'Right of human workers and unions.', 'Derecho de trabajadores humanos y organizaciones sindicales.', 'Not applicable to software.', 'No aplica al software.', 'H'],
  [86, 6, 'Grievance procedure', 'Procedimiento de quejas', 'Channel for a person to contest decisions or conditions.', 'Canal para que una persona reclame decisiones o condiciones.', 'Not applicable subjectively to the AI; human channels must exist to contest its actions.', 'No aplica subjetivamente al AI; sí deben existir canales humanos para reclamar acciones del AI.', 'H'],
  [87, 6, 'Protection against harassment', 'Protección contra acoso', 'Human right to an environment free of harassment.', 'Derecho humano a un entorno libre de acoso.', 'Not applicable to the AI as victim; its outputs must be governed so as not to harass humans.', 'No aplica al AI como víctima; sí sus outputs deben estar gobernados para no acosar a humanos.', 'H'],
  [88, 6, 'Due disciplinary process', 'Debido proceso disciplinario', 'Human protection against disciplinary measures.', 'Protección humana ante medidas disciplinarias.', 'Not a right of software; operationally replaced by incident review and change control.', 'No aplica como derecho del software; operacionalmente se reemplaza por incident review y change control.', 'A'],

  [89, 7, 'Segregation of access', 'Segregación de accesos', 'Limit and separate privileges by role.', 'Limitar y separar privilegios según rol.', 'Fundamental: identity, RBAC, scopes and separated secrets.', 'Fundamental: identity, RBAC, scopes y secrets separados.', 'U'],
  [90, 7, 'Audit', 'Auditoría', 'Independent review of processes and decisions.', 'Revisión independiente de procesos y decisiones.', 'Logs, traces, event history, evals and reproducibility.', 'Logs, traces, event history, evals y reproducibilidad.', 'U'],
  [91, 7, 'Traceability', 'Trazabilidad', 'Know who did what, when and under what authority.', 'Saber quién hizo qué, cuándo y bajo qué autoridad.', 'Actor ID + action + timestamp + context + tool + approval, plus the policy and versions in force.', 'Actor ID + action + timestamp + context + tool + approval, más la política y versiones vigentes.', 'U'],
  [92, 7, 'Accountability', 'Accountability', 'There must be a person responsible for decisions and results.', 'Debe existir una persona responsable de decisiones y resultados.', 'Never orphaned: an accountable human answers for deployment, authority and outcomes.', 'Nunca debe quedar huérfano: un humano accountable responde por deployment, authority y outcomes.', 'U'],
  [93, 7, 'Incident management', 'Gestión de incidentes', 'Detect, contain, investigate and learn from failures.', 'Detectar, contener, investigar y aprender de fallas.', 'AI incident management with kill switch, rollback, postmortem and remediation.', 'AI incident management con kill switch, rollback, postmortem y remediation.', 'U'],
  [94, 7, 'Data protection', 'Protección de datos', 'Privacy, access, minimisation and retention principles.', 'Principios de privacidad, acceso, minimización y retención.', 'Data governance, consent, retrieval filters, retention and deletion.', 'Data governance, consent, retrieval filters, retention y deletion.', 'U'],
  [95, 7, 'Risk management', 'Gestión de riesgo', 'Identify, assess, mitigate and monitor exposure.', 'Identificar, evaluar, mitigar y monitorear exposición.', 'Risk classification by role, tool, data and action; proportional controls.', 'Risk classification por rol, tool, data y action; controles proporcionales.', 'U'],

  [96, 8, 'Promotion', 'Promoción', 'More responsibility, scope, status or compensation.', 'Mayor responsabilidad, alcance, estatus o compensación.', 'More scope, autonomy, budget or authority after evidence.', 'Mayor scope, autonomy, budget o authority tras evidencia.', 'A'],
  [97, 8, 'Post transfer', 'Transferencia de puesto', 'Change of function or unit.', 'Cambio de función o unidad.', 'New Role Contract, tools, context, permissions and manager.', 'Nuevo Role Contract, tools, context, permissions y manager.', 'U'],
  [98, 8, 'Succession plan', 'Plan de sucesión', 'Prepare a replacement for critical talent.', 'Preparar reemplazo para talento crítico.', 'Fallback agent/model/version and replacement runbook.', 'Fallback agent/model/version y runbook de reemplazo.', 'U'],
  [99, 8, 'Cross-training', 'Cross-training', 'Develop flexibility to cover other functions.', 'Desarrollar flexibilidad para cubrir otras funciones.', 'Multi-capability, backup agents or ensembles, minding separation of duties.', 'Multi-capability, backup agents o ensembles, cuidando separation of duties.', 'U'],
  [100, 8, 'Retention of critical talent and knowledge', 'Retención de talento/conocimiento crítico', 'Reduce loss of capabilities and know-how.', 'Reducir pérdida de capacidades y know-how.', 'Reduce vendor/model lock-in; preserve prompts, policies, evals, memory and artifacts.', 'Reducir vendor/model lock-in; preservar prompts, policies, evals, memory y artifacts.', 'A'],
  [101, 8, 'Termination criteria', 'Criterios de terminación', 'Underperformance, restructuring, breach or other causes.', 'Bajo desempeño, reestructuración, incumplimiento u otras causas.', 'Obsolescence, cost, risk, incidents, underperformance or architecture change.', 'Obsolescencia, costo, riesgo, incidents, bajo desempeño o cambio de arquitectura.', 'U'],
  [102, 8, 'Offboarding', 'Offboarding', 'Recover equipment, access, obligations and responsibilities.', 'Recuperar equipos, accesos, obligaciones y responsabilidades.', 'Revoke credentials, disable tools, remove schedules, queues and integrations.', 'Revoke credentials, disable tools, remove schedules, queues y integrations.', 'U'],
  [103, 8, 'Knowledge transfer', 'Transferencia de conocimiento', 'Avoid loss of information on exit.', 'Evitar pérdida de información al salir.', 'Export approved memory, context, artifacts, runbooks and outstanding tasks.', 'Exportar memory aprobada, context, artifacts, runbooks y outstanding tasks.', 'U'],
  [104, 8, 'Information protection after exit', 'Protección de información después de la salida', 'Confidentiality and closing of access.', 'Confidencialidad y cierre de accesos.', 'Retention/deletion policies, revocation and secret rotation.', 'Retention/deletion policies, revocation y secret rotation.', 'U'],
  [105, 8, 'Historical record', 'Registro histórico', 'Employee file and evidence of performance.', 'Employee file y evidencia de desempeño.', 'Versioned audit/performance record for governance and learning.', 'Audit/performance record versionado para governance y aprendizaje.', 'U'],

  [106, 9, 'Plan future capacity', 'Planificar capacidad futura', 'Headcount, skills and load required by the strategy.', 'Headcount, skills y carga requeridos para la estrategia.', 'Human + AI capacity planning, concurrency and workload forecasting.', 'Human + AI capacity planning, concurrency y workload forecasting.', 'U'],
  [107, 9, 'Make vs. buy', 'Make vs. buy', 'Hire, outsource or develop capability internally.', 'Contratar, tercerizar o desarrollar capacidad internamente.', 'Build agent vs. SaaS/vendor vs. managed service vs. open source.', 'Build agent vs. SaaS/vendor vs. managed service vs. open source.', 'U'],
  [108, 9, 'Sizing', 'Dimensionamiento', 'Number and mix of people required.', 'Número y mezcla de personas necesarias.', 'Instances, concurrency, model tiers and required capacity.', 'Instances, concurrency, model tiers y capacity requerida.', 'U'],
  [109, 9, 'Design the workforce mix', 'Diseñar el workforce mix', 'Full-time, part-time, contractors, outsourcing.', 'Full-time, part-time, contractors, outsourcing.', 'Human, AI and hybrid role allocation by risk, cost and comparative advantage.', 'Human, AI y hybrid role allocation según riesgo, costo y ventaja comparativa.', 'U'],
  [110, 9, 'Productivity per resource', 'Productividad por recurso', 'Output/FTE and value generated.', 'Output/FTE y valor generado.', 'Outcome/AI Employee, cost per outcome and human review load.', 'Outcome/AI Employee, cost per outcome y human review load.', 'U'],

  [111, 10, 'Measure productivity', 'Medir productividad', 'Quantity or value of output per resource.', 'Cantidad/valor de output por recurso.', 'Outcomes per unit of cost/time of the AI Employee.', 'Outcomes por unidad de costo/tiempo del AI Employee.', 'U'],
  [112, 10, 'Measure quality', 'Medir calidad', 'Quality against the standard of the post.', 'Calidad contra estándar del puesto.', 'Accuracy, acceptance rate, QA score and policy compliance.', 'Accuracy, acceptance rate, QA score y policy compliance.', 'U'],
  [113, 10, 'Measure cost', 'Medir costo', 'Total and marginal cost of operating the post.', 'Costo total y marginal de operar el puesto.', 'Model + compute + tools + integrations + supervision + error cost.', 'Model + compute + tools + integrations + supervision + error cost.', 'U'],
  [114, 10, 'Measure errors', 'Medir errores', 'Error rate, rework and incidents.', 'Error rate, retrabajo e incidentes.', 'Hallucination/error rate, exception rate, incidents and recovery cost.', 'Hallucination/error rate, exception rate, incidents y recovery cost.', 'U'],
  [115, 10, 'Measure availability', 'Medir disponibilidad', 'Attendance and coverage of the human resource.', 'Asistencia/cobertura del recurso humano.', 'Uptime, queue readiness, dependency availability.', 'Uptime, queue readiness, dependency availability.', 'U'],
  [116, 10, 'Measure utilisation', 'Medir utilización', 'Capacity used versus available.', 'Capacidad utilizada versus disponible.', 'Runtime/concurrency/tool utilisation and idle capacity.', 'Runtime/concurrency/tool utilization e idle capacity.', 'U'],
  [117, 10, 'Measure time to competence', 'Medir tiempo a competencia', 'Time-to-productivity of a new hire.', 'Time-to-productivity de una nueva contratación.', 'Time-to-autonomy: from instantiation to reliable performance.', 'Time-to-autonomy: desde instanciación hasta desempeño confiable.', 'U'],
  [118, 10, 'Measure turnover and replacement', 'Medir rotación/reemplazo', 'Turnover and its causes and costs.', 'Turnover y sus causas/costos.', 'Model/agent replacement rate, architecture churn and migration cost.', 'Model/agent replacement rate, architecture churn y migration cost.', 'A'],
  [119, 10, 'Benchmarking', 'Benchmarking', 'Compare performance between people, teams or market.', 'Comparar desempeño entre personas, equipos o mercado.', 'Compare models, configurations, prompts, agent versions and vendors.', 'Comparar models, configurations, prompts, agent versions y vendors.', 'U'],
  [120, 10, 'Continuous improvement', 'Mejora continua', 'Optimise processes and workforce with evidence.', 'Optimizar procesos y workforce con evidencia.', 'Continuous evals, optimisation, policy iteration and process redesign.', 'Continuous evals, optimization, policy iteration y process redesign.', 'U'],
];

export const PRINCIPLES: Principle[] = ROWS.map(
  ([n, domain, pEn, pEs, hEn, hEs, aEn, aEs, cls]) => ({
    n,
    domain,
    principle: { en: pEn, es: pEs },
    human: { en: hEn, es: hEs },
    artificial: { en: aEn, es: aEs },
    cls,
  }),
);

export const COUNTS = {
  U: PRINCIPLES.filter((p) => p.cls === 'U').length,
  A: PRINCIPLES.filter((p) => p.cls === 'A').length,
  H: PRINCIPLES.filter((p) => p.cls === 'H').length,
};

export const MATRIX_CAVEAT: T = {
  en: 'The matrix is an original synthesis of organisational design, HR, performance management, governance, workforce planning and risk practice. It is not a transcription of any single existing standard, and the classification is a working proposal of this framework — administrative doctrine, not a legal claim about the employment of software.',
  es: 'La matriz es una síntesis propia de prácticas de diseño organizacional, RR. HH., performance management, gobierno, workforce planning y riesgo. No es la transcripción de un único estándar existente, y la clasificación es una propuesta de trabajo de este framework — doctrina administrativa, no una afirmación jurídica sobre el empleo de software.',
};
